directory:
  - .
branch: main
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- all
mask: []
secrets-scan-file-type: []
summary-position: top
skip-check:
  - CKV2_AWS_14  # only machine accounts are being created by the pipeline
  - CKV2_AWS_21
  - CKV2_AWS_22
  - CKV_AWS_273
